Repository X-lab2017/open-digger, pull requests merged in 2020-12, with the labels that each got.

#227 changes for top repos and develop
  sqls/activity-repo-top/post-processor.js
  sqls/activity-repo-top/sql
  sqls/developers-top/post-processor.js
  sqls/developers-top/sql
Labels: pull/approved, pull/sql, pull/sql-runned, pull/sql-verified

#239 [Feature] Case study basic files
  case-study/ASF/REPORT_TEMPLATE.md
  case-study/ASF/manifest.json
  case-study/CNCF/REPORT_TEMPLATE.md
  case-study/LFAIData/REPORT_TEMPLATE.md
  case-study/Wuhan2020/REPORT_TEMPLATE.md
Labels: kind/feature, pull/approved

#246 Update REPORT_TEMPLATE.md
  case-study/Wuhan2020/REPORT_TEMPLATE.md
Labels: pull/approved

#248 Update REPORT_TEMPLATE.md
  case-study/Wuhan2020/REPORT_TEMPLATE.md
Labels: pull/approved

#255 [Feature] Case study hypertrons component
  .github/hypertrons-components/auto_update_case_study/config.ts
  .github/hypertrons-components/auto_update_case_study/defaultConfig.ts
  .github/hypertrons-components/auto_update_case_study/index.lua
  .github/hypertrons-components/auto_update_case_study/version.json
  case-study/sqls/activity-repo/manifest.json
  case-study/sqls/activity-repo/post-processor.js
  case-study/sqls/activity-repo/sql
Labels: kind/feature, pull/hypertrons

#252 [Docs] add incubate procedure
  case-study/LFAIData/REPORT_TEMPLATE.md
Labels: area/document, pull/approved

#260 [Refactor] Add activity to ASF
  case-study/ASF/REPORT_TEMPLATE.md
Labels: kind/enhancement

#263 [Docs] add CNCF report template and manifest
  case-study/CNCF/REPORT_TEMPLATE.md
  case-study/CNCF/manifest.json
Labels: area/document, pull/approved

#267 [Feature] Add pre processor
  .github/hypertrons-components/auto_update_report/config.ts
  .github/hypertrons-components/auto_update_report/defaultConfig.ts
  .github/hypertrons-components/auto_update_report/index.lua
Labels: kind/feature, pull/hypertrons

#262 [Feature] Language distribution of Top 100000 repos
  REPORT_TEMPLATE.md
  sqls/language-distribution/manifest.json
  sqls/language-distribution/post-processor.js
  sqls/language-distribution/sql
Labels: kind/feature, pull/approved, pull/sql, pull/sql-runned, pull/sql-verified

#272 Update REPORT_TEMPLATE.md
  case-study/Wuhan2020/REPORT_TEMPLATE.md
Labels: pull/approved

#270 [Docs] update LFAI
  case-study/LFAIData/REPORT_TEMPLATE.md
  case-study/LFAIData/manifest.json
Labels: area/document, pull/approved

#251 add Chinese info
  REPORT_TEMPLATE.md
  sqls/activity-repo-top-Chinese/manifest.json
  sqls/activity-repo-top-Chinese/post-processor.js
  sqls/activity-repo-top-Chinese/pre-processor.js
  sqls/activity-repo-top-Chinese/sql
  sqls/activity-repo-top/sql
Labels: pull/approved, pull/sql, pull/sql-runned

#271 Update REPORT_TEMPLATE.md
  case-study/Wuhan2020/REPORT_TEMPLATE.md
Labels: pull/approved

#279 [Docs] Add case study to website
  docs/_sidebar.md
  docs/case-study/CNCF.md
  docs/case-study/LFAI.md
  docs/case-study/Wuhan2020.md
  docs/index.html
  docs/zh-cn/_sidebar.md
  docs/zh-cn/case-study/CNCF.md
  docs/zh-cn/case-study/LFAI.md
  docs/zh-cn/case-study/Wuhan2020.md
Labels: area/document, pull/approved, pull/website
