Repository X-lab2017/open-digger, pull requests merged in 2020-09, with the labels that each got.

#59 [Refactor] Contribution sort alphabetically if score is equal
  .github/hypertrons-components/auto_update_contribution/index.lua
Labels: kind/enhancement, pull/approved, pull/hypertrons

#76 [Refactor] change base url
  docs/architecture.md
  docs/workflow.md
  docs/zh-cn/architecture.md
  docs/zh-cn/workflow.md
Labels: kind/enhancement, pull/approved, pull/website

#81 [Refactor] Change 2020 to analysis report for any period
  README.md
  REPORT_TEMPLATE.md
  docs/README.md
  docs/_coverpage.md
  docs/architecture.md
  docs/diagrams/architect.uml
  docs/index.html
  docs/workflow.md
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  docs/zh-cn/architecture.md
  docs/zh-cn/workflow.md
Labels: kind/enhancement, pull/approved, pull/website

#84 [Docs] Add website readme
  docs/README.md
  docs/zh-cn/README.md
Labels: area/document, pull/approved, pull/website

#85 docs: add contributing guide.
  docs/CONTRIBUTING.md
  docs/zh-cn/CONTRIBUTING.md
Labels: area/document, pull/approved, pull/website

#90 [Refactor] Add more param to sql run
  .github/hypertrons-components/auto_update_report/defaultConfig.ts
  .github/hypertrons-components/sql_run/defaultConfig.ts
  .github/hypertrons-components/sql_run/index.lua
Labels: kind/enhancement, pull/approved, pull/hypertrons

#89 [Feature] Add working hour sql component
  .github/hypertrons-components/sql_run/defaultConfig.ts
  sqls/working-hour-distribution/image.svg
  sqls/working-hour-distribution/manifest.json
  sqls/working-hour-distribution/post-processor.js
  sqls/working-hour-distribution/sql
Labels: kind/feature, pull/approved, pull/hypertrons, pull/sql, pull/sql-runned, pull/sql-verified

#91 [Docs] Add working hour to report template
  REPORT_TEMPLATE.md
Labels: area/document, pull/approved

#96 [Fix] Fix few things about working hour
  .github/hypertrons-components/auto_update_report/index.lua
  REPORT_TEMPLATE.md
  docs/_sidebar.md
  docs/report.md
  sqls/working-hour-distribution/image.svg
  sqls/working-hour-distribution/post-processor.js
  sqls/working-hour-distribution/sql
Labels: pull/approved, pull/hypertrons, pull/sql-runned, pull/sql-verified, pull/website

#109 [Docs] Add word cloud for GitHub
  .github/hypertrons-components/auto_update_report/config.ts
  .github/hypertrons-components/auto_update_report/defaultConfig.ts
  .github/hypertrons-components/auto_update_report/index.lua
  REPORT_TEMPLATE.md
  docs/report.md
  docs/word-cloud.html
Labels: area/document, pull/approved, pull/hypertrons

#113 [Docs]Add word cloud description
  REPORT_TEMPLATE.md
Labels: area/document, pull/approved, pull/website
