Repository X-lab2017/open-digger, pull requests merged in 2020-08, with the labels that each got.

#29 docs:add slack link
  README.md
Labels: pull/approved

#26 [Docs] Add cc by 4 license and badge
  LICENSE-CC-BY
  README.md
Labels: area/document, pull/approved

#33 docs: add architecture and contents
  docs/README.md
  docs/_sidebar.md
  docs/architecture.md
  docs/diagrams/architect.uml
  docs/index.html
  docs/zh-cn/.nojekyll
  docs/zh-cn/README.md
  docs/zh-cn/_coverpage.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/architecture.md
Labels: area/document, pull/approved

#31 [Refactor] Change number to thousand format.
  sqls/total-developer-count/post-processor.js
  sqls/total-record-count/post-processor.js
  sqls/total-repo-count/post-processor.js
Labels: kind/enhancement, pull/approved, pull/sql, pull/sql-runned, pull/sql-verified

#37 [Docs] Add workflow docs
  docs/diagrams/pull-flow.uml
  docs/workflow.md
  docs/zh-cn/workflow.md
Labels: area/document

#48 [Docs] Change slack join link to badge
  README.md
Labels: area/document, pull/approved

#35 [Feature] Add pr uml render component
  .github/hypertrons-components/sql_label/index.lua
  .github/hypertrons.json
Labels: kind/feature, pull/approved

#49 [Feature] Add pr file label config
  .github/hypertrons-components/sql_label/config.ts
  .github/hypertrons-components/sql_label/defaultConfig.ts
  .github/hypertrons-components/sql_label/index.lua
  .github/hypertrons-components/sql_label/version.json
  .github/hypertrons.json
Labels: kind/feature, pull/approved

#32 docs(documentations):add a draft for data description#23
  docs/DATA.md
  docs/csv/data_description.csv
  docs/pic/GHArchive_raw_data.png
  docs/pic/database_table_1.png
  docs/pic/databse_table_2.png
Labels: area/document
