Repository X-lab2017/open-digger, pull requests merged in 2021-07, with the labels that each got.

#606 Feature:add sofastack weekly report
  case-study/cases/sofastack.yaml
  case-study/sqls/org-weekly-report/processor.js
  package-lock.json
  package.json
  src/pageUtils.ts
Labels: kind/feature, pull/approved

#617 [Docs] update_slack_link & update_meeting_record
  README.md
  docs/community_meeting_record.yaml
Labels: area/document, pull/approved, pull/website

#628 add meeting video list & update qrcode
  README.md
  docs/assets/wechat-qrcode.png
Labels: pull/approved, pull/website
