Repository X-lab2017/open-digger, pull requests merged in 2021-11, with the labels that each got.

#663 Move Apache ShardingSphere to None company
  case-study/cases/Chinese.yaml
Labels: pull/approved

#673 [Refactor] Update oss actions workflow
  .github/workflows/publish.yml
Labels: kind/enhancement

#672 [Feature]Add ossrs into Chinese list
  case-study/cases/Chinese.yaml
Labels: pull/approved, kind/feature

#678 Add new issue templates for submitting labeled data and ordinary issue
  .github/ISSUE_TEMPLATE/ordinary_issue.md
  .github/ISSUE_TEMPLATE/submit_labeled_data.md
Labels: pull/approved
