Repository X-lab2017/open-digger, pull requests merged in 2022-04, with the labels that each got.

#809 [Feature] Add CI test for label data PR
  .github/workflows/check_label_pr.yml
  package-lock.json
  package.json
  src/ci/pull_label_file_test.ts
  src/ci/utils.ts
  src/config.ts
Labels: kind/feature

#802 Add one more org which belongs to QingCloud
  labeled_data/companies/qingcloud/index.yml
Labels: pull/approved

#801 Add a new company which comes from China
  labeled_data/companies/merico/index.yml
Labels: pull/approved

#812 refactor: remove 0 values from hypercrx data
  src/cron/tasks/hypercrx_actor.ts
  src/cron/tasks/hypercrx_repo.ts
Labels: kind/enhancement
