Repository X-lab2017/open-digger, pull requests merged in 2022-09, with the labels that each got.

#955 【Hackathon No.87】 Paddle 社区数据分析
  events/paddle_hackathon_3rd/87_PureNatural.ipynb
Labels: pull/approved

#970 【Hackathon No.88】：Paddle 社区开发者行为可视化
  events/paddle_hackathon_3rd/88_Swift.ipynb
Labels: pull/approved

#982 fix: update data_description.csv
  docs/assets/data_description.csv
Labels: kind/bug, pull/website

#983 docs: update community_meeting_records.yaml
  docs/community_meeting_record.yaml
Labels: kind/community, area/document, pull/website
