Repository X-lab2017/open-digger, pull requests merged in 2022-03, with the labels that each got.

#743 [Feature] Add activity and openrank support
  notebook/example.ipynb
  notebook/handbook.ipynb
  src/label_data_utils.ts
  src/metrics/related_users.ts
  src/open_digger.js
Labels: kind/feature

#746 [Feature] Add hacking hero support
  notebook/hacking_heros.ipynb
  src/config.ts
  src/db/clickhouse.ts
  src/db/neo4j.ts
Labels: kind/feature

#756 Add new Amazon open source orgs
  labeled_data/companies/amazon/index.yml
Labels: pull/approved

#757 [Doc] Update issue template
  .github/ISSUE_TEMPLATE/submit_chinese_developer_data.md
Labels: area/document

#760 Add Netflix and update VMWare label data
  labeled_data/companies/netflix/index.yml
  labeled_data/companies/vmware/index.yml
Labels: pull/approved

#772 [Feature] Add oss client and hypercrx task
  package-lock.json
  package.json
  src/config.ts
  src/cron/tasks/hacking_force_month.ts
  src/cron/tasks/hypercrx_actor.ts
  src/cron/tasks/hypercrx_repo.ts
  src/db/clickhouse.ts
  src/db/neo4j.ts
  src/oss/ali.ts
  src/utils.ts
Labels: kind/feature

#773 [Community] Change role of the community
  .github/hypertrons.json
Labels: kind/community, pull/hypertrons

#775 [Doc] Update wechat qrcode
  README.md
  docs/assets/wechat-qrcode.png
Labels: area/document, pull/website

#777 [Feature] Add hacking force annual task
  labeled_data/companies/hashicorp/index.yml
  src/cron/tasks/hacking_force_annual.ts
Labels: kind/feature

#785 [Docs] Update qrcode
  README.md
  docs/assets/wechat-qrcode.png
Labels: area/document, pull/website

#795 refactor: change hypercrx time span
  src/cron/tasks/hypercrx_actor.ts
  src/cron/tasks/hypercrx_repo.ts
  src/cron/tasks/open_leaderboard.ts
Labels: kind/enhancement

#796 doc: modify readme
  .github/hypertrons-components/sql_verified/config.ts
  .github/hypertrons-components/sql_verified/defaultConfig.ts
  .github/hypertrons-components/sql_verified/index.lua
  .github/hypertrons-components/sql_verified/version.json
  .github/workflows/pr_test.yml
  .github/workflows/publish.yml
  README.md
  notebook/China_open_source_blue_paper_2022.ipynb
  notebook/China_open_source_report_2021.ipynb
Labels: area/document, pull/hypertrons

#797 fix: hypertrons update contribution config
  .github/hypertrons-components/auto_update_contribution/defaultConfig.ts
Labels: kind/bug, pull/hypertrons

#800 Add more GitHub organization accounts of QingCloud
  labeled_data/companies/qingcloud/index.yml
Labels: pull/approved
