Repository X-lab2017/open-digger, pull requests merged in 2022-05, with the labels that each got.

#828 fix: fix bad link in doc
  docs/zh-cn/data.md
Labels: kind/bug, area/document, pull/website

#829 fix: fix data description in English version doc
  docs/DATA.md
Labels: kind/bug, area/document, pull/website

#833 [docs] Add 'events' website page to distrbute Summer 2022 participation
  docs/zh-cn/_sidebar.md
  docs/zh-cn/events.md
Labels: pull/approved, area/document, pull/website

#840 Add a new GitHub org which belong to QingCloud
  labeled_data/companies/qingcloud/index.yml
Labels: pull/approved

#845 refactor: change to new database schema
  docs/assets/data_description.csv
  docs/data.md
  docs/zh-cn/data.md
  notebook/China_open_source_blue_paper_2022.ipynb
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  notebook/supply_chain_report_2021.ipynb
  src/metrics/activity_openrank.ts
Labels: kind/enhancement, pull/website
