Repository X-lab2017/open-digger, pull requests merged in 2022-06, with the labels that each got.

#849 fix: fix data link in readme
  README.md
Labels: kind/bug

#850 doc: add clickhouse demo notebook
  README.md
Labels: area/document

#853 data: move openmmlab to community
  labeled_data/communities/openmmlab/index.yml
  labeled_data/regions/China.yml
Labels: kind/community

#858 fix: fix dockerfile and doc
  sample_data/README.md
  sample_data/build/build_image_arm.sh
Labels: kind/bug, area/document

#859 doc: update
  README.md
  sample_data/README.md
Labels: area/document

#862 refactor: optimize clickhouse sql
  notebook/China_open_source_blue_paper_2022.ipynb
  package.json
  src/config.ts
  src/cron/tasks/open_leaderboard.ts
  src/label_data_utils.ts
  src/metrics/activity_openrank.ts
  src/metrics/basic.ts
  src/metrics/index.ts
  src/metrics/related_users.ts
  src/open_digger.js
  src/utils.ts
Labels: kind/enhancement

#863 fix: fix some neo4j query
  src/metrics/activity_openrank.ts
  src/metrics/related_users.ts
Labels: kind/bug

#873 docs: Add document for Jupyter Notebook image usage (#860)
  sample_data/README.md
Labels: pull/approved, area/document

#877 [document] Update sample data and notebook usage
  sample_data/README.md
Labels: pull/approved, area/document

#876 feat: Implement Issues Closed Metric
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#889 Update GitHub username
  .github/hypertrons.json
Labels: pull/approved, pull/hypertrons
