Repository X-lab2017/open-digger, pull requests merged in 2022-08, with the labels that each got.

#933 Metric: change requests declined
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#934 Update index.ts
  src/metrics/index.ts
Labels: pull/approved

#935 data: x-lab community data update
  notebook/community_analysis/all_data.json
  notebook/community_analysis/xlab.ipynb
  src/metrics/activity_openrank.ts
Labels: kind/community

#942 fix: fix path problem under windows env
  src/label_data_utils.ts
Labels: kind/question, kind/bug

#944 data: Add mulan community
  labeled_data/communities/mulan/index.yml
  labeled_data/regions/China.yml
Labels: kind/community

#945 fix: fix openrank label slice
  src/metrics/activity_openrank.ts
Labels: kind/bug
