Repository X-lab2017/open-digger, pull requests merged in 2022-11, with the labels that each got.

#1037 metric:code change lines
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#1036 feat: new export method
  package.json
  src/config.ts
  src/cron/index.ts
  src/cron/tasks/hacking_force_annual.ts
  src/cron/tasks/hacking_force_month.ts
  src/cron/tasks/hypercrx_actor.ts
  src/cron/tasks/hypercrx_repo.ts
  src/cron/tasks/monthly_export.ts
  src/cron/tasks/open_leaderboard.ts
  src/db/clickhouse.ts
  src/metrics/attention.ts
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
Labels: pull/approved

#1035 fix: separate python kernel
  .gitignore
  python/README.md
  python/config.py
  python/db/clickhouse.py
  python/db/neo4j_driver.py
  python/label_data_utils.py
  python/metrics/activity_openrank.py
  python/metrics/attention.py
  python/metrics/basic.py
  python/metrics/chaoss.py
  python/metrics/index.py
  python/metrics/related_users.py
  python/open_digger.py
Labels: pull/approved, kind/bug

#1049 fix: precision and names in query option
  notebook/community_analysis/all_data.json
  notebook/community_analysis/xlab.ipynb
  notebook/coss.ipynb
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/cron/tasks/open_leaderboard.ts
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
Labels: pull/approved, kind/bug

#1052 data: add big data label data
  labeled_data/technology/big_data/analysis_engine.yml
  labeled_data/technology/big_data/data_development.yml
  labeled_data/technology/big_data/data_integration.yml
  labeled_data/technology/big_data/data_storage.yml
  labeled_data/technology/big_data/index.yml
  labeled_data/technology/big_data/others.yml
  labeled_data/technology/big_data/scheduler.yml
  labeled_data/technology/big_data/streaming.yml
  labeled_data/technology/big_data/visualization.yml
  src/label_data_utils.ts
Labels: pull/approved

#1056 data: add database label data
  labeled_data/technology/database/content.yml
  labeled_data/technology/database/document.yml
  labeled_data/technology/database/event.yml
  labeled_data/technology/database/graph.yml
  labeled_data/technology/database/index.yml
  labeled_data/technology/database/key_value.yml
  labeled_data/technology/database/multivalue.yml
  labeled_data/technology/database/native_xml.yml
  labeled_data/technology/database/object_oriented.yml
  labeled_data/technology/database/rdf.yml
  labeled_data/technology/database/relational.yml
  labeled_data/technology/database/search_engine.yml
  labeled_data/technology/database/spatial.yml
  labeled_data/technology/database/time_series.yml
  labeled_data/technology/database/wide_column.yml
Labels: pull/approved

#1054 data: add cloud native label data
  labeled_data/technology/cloud_native/app_definition_and_development/application_definition_and_image_build.yml
  labeled_data/technology/cloud_native/app_definition_and_development/continuous_integration_and_delivery.yml
  labeled_data/technology/cloud_native/app_definition_and_development/database.yml
  labeled_data/technology/cloud_native/app_definition_and_development/index.yml
  labeled_data/technology/cloud_native/app_definition_and_development/streaming_and_messaging.yml
  labeled_data/technology/cloud_native/index.yml
  labeled_data/technology/cloud_native/observability_and_analysis/chaos_engineering.yml
  labeled_data/technology/cloud_native/observability_and_analysis/continuous_optimization.yml
  labeled_data/technology/cloud_native/observability_and_analysis/index.yml
  labeled_data/technology/cloud_native/observability_and_analysis/logging.yml
  labeled_data/technology/cloud_native/observability_and_analysis/monitoring.yml
  labeled_data/technology/cloud_native/observability_and_analysis/tracing.yml
  labeled_data/technology/cloud_native/orchestration_and_management/api_gateway.yml
  labeled_data/technology/cloud_native/orchestration_and_management/coordination_and_service_discovery.yml
  labeled_data/technology/cloud_native/orchestration_and_management/index.yml
  labeled_data/technology/cloud_native/orchestration_and_management/remote_procedure_call.yml
  labeled_data/technology/cloud_native/orchestration_and_management/scheduling_and_orchestration.yml
  labeled_data/technology/cloud_native/orchestration_and_management/service_mesh.yml
  labeled_data/technology/cloud_native/orchestration_and_management/service_proxy.yml
  labeled_data/technology/cloud_native/platform/certified_kubernetes_distribution.yml
  labeled_data/technology/cloud_native/platform/certified_kubernetes_hosted.yml
  labeled_data/technology/cloud_native/platform/certified_kubernetes_installer.yml
  labeled_data/technology/cloud_native/platform/index.yml
  labeled_data/technology/cloud_native/platform/paas_and_container_service.yml
  labeled_data/technology/cloud_native/provisioning/automation_and_configuration.yml
  labeled_data/technology/cloud_native/provisioning/container_registry.yml
  labeled_data/technology/cloud_native/provisioning/index.yml
  labeled_data/technology/cloud_native/provisioning/key_management.yml
  labeled_data/technology/cloud_native/provisioning/security_and_compliance.yml
  labeled_data/technology/cloud_native/runtime/cloud_native_network.yml
  labeled_data/technology/cloud_native/runtime/cloud_native_storage.yml
  labeled_data/technology/cloud_native/runtime/container_runtime.yml
  labeled_data/technology/cloud_native/runtime/index.yml
  labeled_data/technology/cloud_native/serverless/framework.yml
  labeled_data/technology/cloud_native/serverless/hosted_platform.yml
  labeled_data/technology/cloud_native/serverless/index.yml
  labeled_data/technology/cloud_native/serverless/installable_platform.yml
  labeled_data/technology/cloud_native/serverless/tools.yml
  labeled_data/technology/cloud_native/wasm/index.yml
  labeled_data/technology/cloud_native/wasm/installable_platform.yml
  labeled_data/technology/cloud_native/wasm/packaging_registries_and_application_delivery.yml
  labeled_data/technology/cloud_native/wasm/runtime.yml
  labeled_data/technology/cloud_native/wasm/specifications.yml
  labeled_data/technology/cloud_native/wasm/toolchain.yml
  src/label_data_utils.ts
Labels: pull/approved

#1061 doc: add metrics usage to readme.
  README.md
Labels: area/document

#1058 data: add operating system label data
  labeled_data/technology/operating_system/index.yml
Labels: pull/approved

#1038 metric:new contributors
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#1063 fix metric: issue resolution duration
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
Labels: pull/approved

#1065 implement metric:change requests duration
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#1066 doc: add user section and optimize url
  README.md
Labels: pull/approved, area/document

#1067 refactor: add limitOption to metrics query
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/cron/tasks/open_leaderboard.ts
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
Labels: pull/approved, kind/enhancement

#1073 doc: add citation file
  CITATION.cff
Labels: pull/approved, area/document
