Repository X-lab2017/open-digger, pull requests merged in 2022-07, with the labels that each got.

#901 refactor: add mkdir for leaderboard
  src/cron/tasks/open_leaderboard.ts
Labels: kind/enhancement

#909 notebook: add notebook for x-lab community
  notebook/community_analysis/all_data.json
  notebook/community_analysis/xlab.ipynb
  src/metrics/activity_openrank.ts
Labels: kind/community

#915 [Notebook] Add a warning about the stars counting algorithm
  notebook/clickhouse_demo.ipynb
Labels: pull/approved

#916 [Data] Add my id as X-lab members labeled data into OpenDigger
  labeled_data/communities/xlab/index.yml
Labels: pull/approved

#918 [Doc] Correct an example command line and change some context order of the sample_data/README
  sample_data/README.md
  sample_data/start_server.sh
Labels: pull/approved, area/document

#926 fix: neo4j user condition
  src/metrics/basic.ts
Labels: kind/bug
