Repository X-lab2017/open-digger, pull requests merged in 2022-10, with the labels that each got.

#980 feat: update antgroup data
  labeled_data/companies/alibaba/index.yml
  labeled_data/companies/alibaba/opensumi.yml
  labeled_data/companies/antgroup/index.yml
Labels: pull/approved

#993 fix: Update README.md to fix a bug about the docker image name
  sample_data/README.md
Labels: kind/bug, area/document

#997 Add new committer
  .github/hypertrons.json
Labels: pull/hypertrons

#1000 ci: auto mark issue reply status
  .github/workflows/reply-label-issue-comment.yml
  .github/workflows/reply-label-issue-open.yml
Labels: pull/approved

#1001 Submit a new company GitHub org
  labeled_data/companies/primihub/index.yml
Labels: pull/approved

#998 [Doc] Add python kernel sample data guide.
  sample_data/README.md
Labels: pull/approved, area/document

#1013 docs: fix a broken link in docs/README.md
  docs/README.md
Labels: pull/approved, area/document, pull/website

#1022 update chinese developer label and add issue replier message
  .github/hypertrons.json
  labeled_data/regions/China.yml
Labels: pull/hypertrons
