Repository X-lab2017/open-digger, pull requests merged in 2022-12, with the labels that each got.

#1078 refactor: change the date format for export data
  src/cron/tasks/monthly_export.ts
Labels: pull/approved, kind/enhancement

#1079 fix: minor fix of leaderboard task
  src/cron/tasks/open_leaderboard.ts
Labels: pull/approved, kind/bug

#1080 notebook: update xlab report
  notebook/community_analysis/xlab.ipynb
Labels: pull/approved

#1086 metric：Issue Response Time
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#1096 data: Add 3 orgs into alibaba
  labeled_data/companies/alibaba/index.yml
  labeled_data/companies/hashicorp/index.yml
Labels: pull/approved

#1098 refactor: change underlying clickhouse driver
  notebook/China_open_source_blue_paper_2022.ipynb
  notebook/China_open_source_report_2021.ipynb
  notebook/clickhouse_demo.ipynb
  notebook/coss.ipynb
  notebook/hacking_force.ipynb
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  notebook/supply_chain_report_2021.ipynb
  package-lock.json
  package.json
  src/config.ts
  src/cron/tasks/monthly_export.ts
  src/cron/tasks/open_leaderboard.ts
  src/db/clickhouse.ts
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
  src/oss/ali.ts
  tsconfig.json
Labels: pull/approved, kind/enhancement

#1099 refactor: upgrade sample data docker image and dataset
  sample_data/README.md
  sample_data/build/Dockerfile
  sample_data/build/Dockerfile_arm
  sample_data/build/build_image.sh
  sample_data/build/build_image_arm.sh
  sample_data/build/initdb.sh
  sample_data/export_sample.sh
  sample_data/sql_files/2015_2021_top50_year.sql
  sample_data/sql_files/2020_full.sql
  sample_data/sql_files/label_2015.sql
  sample_data/sql_files/paddle_hackathon_3.sql
  sample_data/sql_files/second_sample.sql
  sample_data/start_server.sh
Labels: pull/approved, kind/enhancement, area/document

#1103 feat: export hypercrx network from neo4j
  src/cron/tasks/network_export.ts
  src/db/neo4j.ts
Labels: pull/approved

#1106 feat: add handle data loss for 2021.10
  src/cron/tasks/monthly_export.ts
Labels: pull/approved

#1108 refactor: add label data to export repo and user
  src/cron/tasks/monthly_export.ts
Labels: pull/approved, kind/enhancement

#1104 refactor: modify node size of networks
  src/cron/tasks/network_export.ts
Labels: pull/approved, kind/enhancement

#1112 data: add repository label data
  labeled_data/application_domain/application_software/index.yml
  labeled_data/application_domain/libraries_and_frameworks/index.yml
  labeled_data/application_domain/non_software/index.yml
  labeled_data/application_domain/software_tools/index.yml
  labeled_data/application_domain/system_software/index.yml
Labels: pull/approved

#1114 feat: cron task for removing rename legacy orgs and repos
  package-lock.json
  package.json
  src/cron/tasks/remove_rename.ts
Labels: pull/approved

#1097 metric: Change request acceptance ratio
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved
