Repository X-lab2017/open-digger, pull requests merged in 2023-02, with the labels that each got.

#1170 Data/update xsosi
  notebook/community_analysis/xlab.ipynb
Labels: pull/approved

#1173 refactor: add reopened action to issues new metric
  src/metrics/chaoss.ts
Labels: pull/approved, kind/enhancement

#1174 fix: use meta.json instead of name.json as flag file
  src/cron/tasks/monthly_export.ts
Labels: pull/approved, kind/bug

#1177 fix: fix bug in project openrank and update xsosi
  notebook/community_analysis/xlab.ipynb
Labels: pull/approved, kind/bug

#1179 doc: add export metrics to readme
  README.md
Labels: pull/approved, area/document

#1181 doc: add more pen demos
  README.md
Labels: pull/approved, area/document

#1182 doc(website): clean useless files and add openrank doc
  assets/working-hour-distribution.svg
  docs/OpenDigger_Community_Handbook.md
  docs/README.md
  docs/_sidebar.md
  docs/assets/architect.uml
  docs/assets/architecture.svg
  docs/assets/gharchive_raw_data.png
  docs/community_meeting_record.yaml
  docs/data.md
  docs/metrics/openrank.md
  docs/word-cloud.html
  docs/workflow.md
  docs/zh-cn/data.md
Labels: pull/approved, area/document, pull/website

#1185 doc(website): add index doc for project openrank
  docs/_sidebar.md
  docs/metrics/openrank.md
  docs/metrics/project_openrank.md
Labels: pull/approved, area/document, pull/website

#1187 feat: add activity developer details option
  src/cron/tasks/monthly_export.ts
  src/metrics/indices.ts
  test/metrics.test.ts
Labels: pull/approved

#1190 data: add new member to xlab
  labeled_data/communities/xlab/index.yml
Labels: pull/approved

#1191 doc(website): add zh doc for openrank
  docs/_sidebar.md
  docs/data.md
  docs/index.html
  docs/metrics/global_openrank.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/data.md
  docs/zh-cn/metrics/global_openrank.md
  docs/zh-cn/metrics/project_openrank.md
Labels: pull/approved, area/document, pull/website

#1192 doc(website): add doc for technical fork
  docs/_sidebar.md
  docs/metrics/technical_fork.md
  package-lock.json
Labels: pull/approved, area/document, pull/website

#1194 doc(website): fix the technical_fork.md codepen display
  docs/metrics/technical_fork.md
Labels: pull/approved, area/document, pull/website

#1196 label: add ai related label data
  labeled_data/companies/amazon/index.yml
  labeled_data/companies/artelnics/index.yml
  labeled_data/companies/deepmind/index.yml
  labeled_data/companies/explosionai/index.yml
  labeled_data/companies/fuzhi/index.yml
  labeled_data/companies/google/index.yml
  labeled_data/companies/h2oai/index.yml
  labeled_data/companies/huawei/index.yml
  labeled_data/companies/intel/index.yml
  labeled_data/companies/microsoft/index.yml
  labeled_data/companies/mycroftai/index.yml
  labeled_data/companies/nvidia/index.yml
  labeled_data/companies/openai/index.yml
  labeled_data/companies/rare/index.yml
  labeled_data/companies/tencent/index.yml
  labeled_data/companies/uber/index.yml
  labeled_data/companies/webank/index.yml
  labeled_data/companies/xiaomi/index.yml
  labeled_data/companies/zalando/index.yml
  labeled_data/regions/America.yml
  labeled_data/regions/China.yml
  labeled_data/regions/Germany.yml
  labeled_data/regions/Spain.yml
  labeled_data/regions/United_kingdom.yml
  labeled_data/technology/ai/index.yml
Labels: pull/approved

#1198 data: add frontend label data
  labeled_data/companies/alibaba/index.yml
  labeled_data/companies/anaconda/index.yml
  labeled_data/companies/antgroup/index.yml
  labeled_data/companies/blue_spire/index.yml
  labeled_data/companies/deno/index.yml
  labeled_data/companies/intel/index.yml
  labeled_data/companies/iqiyi/index.yml
  labeled_data/companies/netlify/index.yml
  labeled_data/companies/tencent/index.yml
  labeled_data/companies/twitter/index.yml
  labeled_data/regions/America.yml
  labeled_data/regions/China.yml
  labeled_data/technology/frontend/index.yml
Labels: pull/approved

#1200 data: add openjs label data
  labeled_data/foundations/openjs.yml
Labels: pull/approved

#1202 doc: fix user codepen url
  README.md
  docs/README.md
Labels: pull/approved, area/document, pull/website

#1203 fix: fix typo in readme
  README.md
  docs/README.md
Labels: pull/approved, kind/bug, pull/website

#1204 doc: update table format
  README.md
  docs/README.md
Labels: pull/approved, area/document, pull/website

#1207 refactor: slice activity detail in case large size file
  src/cron/tasks/monthly_export.ts
Labels: pull/approved, kind/enhancement

#1211 data: add block chain label data
  labeled_data/companies/baidu/index.yml
  labeled_data/companies/jd/index.yml
  labeled_data/technology/blockchain/index.yml
Labels: pull/approved

#1213 data: add iot label data
  labeled_data/companies/espressif/index.yml
  labeled_data/companies/fmsoft/index.yml
  labeled_data/companies/samsung/index.yml
  labeled_data/companies/tencent/index.yml
  labeled_data/technology/iot/index.yml
Labels: pull/approved

#1214 docs(website): add file structure
  docs/_sidebar.md
  docs/file_structure.md
  docs/zh-cn/_sidebar.md
  docs/zh-cn/file_structure.md
Labels: pull/approved, area/document, pull/website
