Repository X-lab2017/open-digger, pull requests merged in 2023-10, with the labels that each got.

#1403 fix: update testdata
  test/metrics.test.ts
  test/testdata/change_request_resolution_duration/change_request_resolution_duration_desc_3_all_null_quarter.json
  test/testdata/change_request_resolution_duration/change_request_resolution_duration_desc_3_all_null_year.json
  test/testdata/change_requests_duration/change_requests_duration_desc_3_all_null_month.json
  test/testdata/change_requests_duration/change_requests_duration_desc_3_all_null_quarter.json
  test/testdata/change_requests_duration/change_requests_duration_desc_3_all_null_year.json
  test/testdata/issue_resolution_duration/issue_resolution_duration_desc_3_all_null_month.json
  test/testdata/issue_resolution_duration/issue_resolution_duration_desc_3_all_null_quarter.json
  test/testdata/issue_resolution_duration/issue_resolution_duration_desc_3_all_null_year.json
  test/testdata/repo_active_dates_and_times/repo_active_dates_and_times_desc_3_all_org_month.json
  test/testdata/repo_active_dates_and_times/repo_active_dates_and_times_desc_3_all_org_quarter.json
  test/testdata/repo_active_dates_and_times/repo_active_dates_and_times_desc_3_all_org_year.json
  test/testdata/user_active_dates_and_times/user_active_dates_and_times_desc_3_all_org_month.json
  test/testdata/user_active_dates_and_times/user_active_dates_and_times_desc_3_all_org_quarter.json
  test/testdata/user_active_dates_and_times/user_active_dates_and_times_desc_3_all_org_year.json
  test/testdata/user_activity/user_activity_desc_3_all_null_month.json
  test/testdata/user_activity/user_activity_desc_3_all_null_quarter.json
  test/testdata/user_activity/user_activity_desc_3_all_null_year.json
Labels: pull/approved, kind/bug

#1409 doc: add repo topic column
  docs/assets/data_description.csv
Labels: area/document

#1417 Update data for Database technical area labled on dbdb.io and DB-Engines Ranking by Oct 27, 2023.
  labeled_data/technology/database/document.yml
  labeled_data/technology/database/key_value.yml
  labeled_data/technology/database/object_oriented.yml
  labeled_data/technology/database/relational.yml
  labeled_data/technology/database/time_series.yml
Labels: pull/approved

#1418 Redesign the categories for generative_ai labels and add new labels
  labeled_data/technology/ai/generative_ai/application/audio.yml
  labeled_data/technology/ai/generative_ai/application/code.yml
  labeled_data/technology/ai/generative_ai/application/image.yml
  labeled_data/technology/ai/generative_ai/application/other.yml
  labeled_data/technology/ai/generative_ai/application/text.yml
  labeled_data/technology/ai/generative_ai/application/video.yml
  labeled_data/technology/ai/generative_ai/infrastructure/data.yml
  labeled_data/technology/ai/generative_ai/infrastructure/document.yml
  labeled_data/technology/ai/generative_ai/infrastructure/platform_and_environment.yml
  labeled_data/technology/ai/generative_ai/infrastructure/vector_database.yml
  labeled_data/technology/ai/generative_ai/model/framework_and_architecture.yml
  labeled_data/technology/ai/generative_ai/model/fundamental_model.yml
  labeled_data/technology/ai/generative_ai/model/variant_model.yml
  labeled_data/technology/ai/generative_ai/music.yml
  labeled_data/technology/ai/generative_ai/tool/deployment_tool.yml
  labeled_data/technology/ai/generative_ai/tool/develop_tool.yml
  labeled_data/technology/ai/generative_ai/tool/production_monitor.yml
  labeled_data/technology/ai/generative_ai/tool/prompt_engineering.yml
Labels: pull/approved
