Repository X-lab2017/open-digger, pull requests merged in 2023-03, with the labels that each got.

#1220 notebook: update xsosi for 2023-02
  notebook/community_analysis/xlab.ipynb
Labels: pull/approved

#1224 docs: Fix qrcode link error
  docs/README.md
Labels: pull/approved, kind/bug, area/document, pull/website

#1223 fix: fix time aggregation for activity
  src/metrics/basic.ts
  src/metrics/indices.ts
Labels: pull/approved, kind/bug

#1229 [Docs] synchronizes chinese version README wht English version
  docs/zh-cn/README.md
Labels: pull/approved, area/document, pull/website

#1236 update label data add new group to alibaba and fit2cloud
  labeled_data/companies/alibaba/index.yml
  labeled_data/companies/fit2cloud/index.yml
Labels: pull/approved
