Repository X-lab2017/open-digger, pull requests merged in 2023-05, with the labels that each got.

#1278 fix: change China to CN and remove 2 missing repos
  labeled_data/technology/database/document.yml
  labeled_data/technology/database/key_value.yml
  src/cron/tasks/monthly_export.ts
  src/cron/tasks/open_leaderboard.ts
Labels: pull/approved, kind/bug

#1273 docs: fix typo of `user login`
  README.md
Labels: pull/approved, area/document

#1282 notebook: update xsosi
  notebook/community_analysis/xlab.ipynb
Labels: pull/approved

#1287 fix:improve application domain label data
  labeled_data/application_domain/application_software/index.yml
  labeled_data/application_domain/libraries_and_frameworks/index.yml
  labeled_data/application_domain/non_software/index.yml
  labeled_data/application_domain/software_tools/index.yml
  labeled_data/application_domain/system_software/index.yml
Labels: pull/approved, kind/bug

#1289 fix:corrected the application label under the system_software file.
  labeled_data/application_domain/application_software/index.yml
  labeled_data/application_domain/libraries_and_frameworks/index.yml
  labeled_data/application_domain/non_software/index.yml
  labeled_data/application_domain/software_tools/index.yml
  labeled_data/application_domain/system_software/index.yml
Labels: pull/approved, kind/bug

#1288 fix: label group error
  src/metrics/basic.ts
Labels: pull/approved, kind/bug

#1284 Update Data: Update labeled data of Opensource DBMS with a github repo link based on dbdb.io and DB-Engines by May 7th, 2023.
  labeled_data/technology/database/array.yml
  labeled_data/technology/database/document.yml
  labeled_data/technology/database/graph.yml
  labeled_data/technology/database/key_value.yml
  labeled_data/technology/database/object_oriented.yml
  labeled_data/technology/database/relational.yml
  labeled_data/technology/database/time_series.yml
  labeled_data/technology/database/wide_column.yml
Labels: pull/approved

#1292 docs: add a row of activity_details to the table in README
  README.md
  docs/README.md
  docs/zh-cn/README.md
Labels: pull/approved, area/document

#1295 [Snyk] Upgrade @clickhouse/client from 0.0.10 to 0.0.15
  package-lock.json
  package.json
Labels: pull/approved

#1281 [Notebook] Add 2023 blue paper notebook
  notebook/China_open_source_blue_paper_2023.ipynb
Labels: pull/approved

#1296 [WIP] docs: Simplified Readme
  README.md
Labels: pull/approved, area/document

#1298 refactor: add more columns in ClickHouse database
  docs/assets/data_description.csv
Labels: pull/approved, kind/enhancement
