Repository X-lab2017/open-digger, pull requests merged in 2023-01, with the labels that each got.

#1117 fix:change application domian data type
  labeled_data/application_domain/application_software/index.yml
  labeled_data/application_domain/libraries_and_frameworks/index.yml
  labeled_data/application_domain/non_software/index.yml
  labeled_data/application_domain/software_tools/index.yml
  labeled_data/application_domain/system_software/index.yml
Labels: pull/approved, kind/bug

#1116 fix: duplicate name in export table
  src/cron/tasks/monthly_export.ts
Labels: pull/approved, kind/bug

#1118 data: add xsosi for xlab 2022-12
  notebook/community_analysis/xlab.ipynb
Labels: pull/approved

#1102 feat: 2022 open source report data section outline
  notebook/China_open_source_report_2022.ipynb
  src/ci/pull_label_file_test.ts
  src/ci/utils.ts
  src/cron/index.ts
  src/cron/tasks/open_leaderboard.ts
  src/db/clickhouse.ts
  src/label_data_utils.ts
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
  src/open_digger.js
  src/utils.ts
Labels: pull/approved

#1123 data: add a new user to china
  labeled_data/regions/China.yml
  src/metrics/index.ts
Labels: pull/approved

#1125 data: add stonedb label
  labeled_data/companies/stoneatom/index.yml
  labeled_data/companies/stoneatom/stonedb.yml
  labeled_data/regions/China.yml
  src/label_data_utils.ts
Labels: pull/approved

#1127 ci: add test to opendigger
  .github/workflows/node_ci.yml
  .mocharc.json
  package-lock.json
  package.json
  sample_data/sql_files/ci_test.sql
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  test/driver.test.ts
  test/label.test.ts
  test/metrics.test.ts
Labels: pull/approved

#1133 doc: add ci badge
  README.md
Labels: pull/approved, area/document

#1131 feat:add application domain repository data analysis
  labeled_data/application_domain/application_software/index.yml
  labeled_data/application_domain/libraries_and_frameworks/index.yml
  labeled_data/application_domain/non_software/index.yml
  labeled_data/application_domain/software_tools/index.yml
  labeled_data/application_domain/system_software/index.yml
  notebook/China_open_source_report_2022.ipynb
Labels: pull/approved

#1134 data: add polardb to alibaba
  labeled_data/companies/alibaba/index.yml
Labels: pull/approved

#1137 data: Update dbms labeled data incrementally based on DB-Engines in Jan, 2023.
  labeled_data/technology/database/key_value.yml
Labels: pull/approved

#1138 data: add kubevela to alibaba
  labeled_data/companies/alibaba/index.yml
Labels: pull/approved

#1132 feat: add bot-lable data #1089
  labeled_data/bot/index.yml
  src/label_data_utils.ts
Labels: pull/approved

#1146 docs: update issue template to yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/cron_task_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/ordinary_issue.md
  .github/ISSUE_TEMPLATE/others.yml
  .github/ISSUE_TEMPLATE/submit_chinese_developer.yml
  .github/ISSUE_TEMPLATE/submit_chinese_developer_data.md
  .github/ISSUE_TEMPLATE/submit_label_data.yml
  .github/ISSUE_TEMPLATE/submit_labeled_data.md
Labels: area/document

#1139 doc: add pull review related columns
  docs/assets/data_description.csv
Labels: pull/approved, area/document, pull/website

#1140 feat: add order option
  .github/workflows/node_ci.yml
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  package.json
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
  test/metrics.test.ts
Labels: pull/approved

#1148 doc:update readme.md in labeled_data
  labeled_data/README.md
Labels: pull/approved, area/document

#1149 metric: add issues active metric
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1147 feat: add new standard to time range metrics
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  test/metrics.test.ts
Labels: pull/approved

#1150 metric: active dates and times
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
Labels: pull/approved

#1152 fix:improve application domain label data
  labeled_data/application_domain/application_software/index.yml
  labeled_data/application_domain/libraries_and_frameworks/index.yml
  labeled_data/application_domain/non_software/index.yml
  labeled_data/application_domain/software_tools/index.yml
  labeled_data/application_domain/system_software/index.yml
  notebook/China_open_source_report_2022.ipynb
Labels: pull/approved, kind/bug

#1151 metric: equivalent time zone
  notebook/handbook.ipynb
  notebook/handbook_zh.ipynb
  src/metrics/index.ts
  src/metrics/metrics.ts
  src/open_digger.js
Labels: pull/approved

#1155 metric: add change request resolution duration
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1156 metric: add change request response time
  .mocharc.json
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1157 metric: add chaoss issue age
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/metrics/indices.ts
  src/metrics/metrics.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1158 metric: add chaoss inactive contributor
  src/metrics/basic.ts
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1159 metric: add contributor email suffix
  src/metrics/index.ts
  src/metrics/metrics.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1162 feat: export more metrics to OSS
  src/cron/tasks/monthly_export.ts
  src/metrics/chaoss.ts
  src/metrics/index.ts
  src/metrics/indices.ts
  src/open_digger.js
  test/metrics.test.ts
Labels: pull/approved

#1166 Remove unmaintained reports
  docs/README.md
Labels: pull/approved, pull/website

#1169 refactor: add export flag file
  src/cron/tasks/monthly_export.ts
Labels: pull/approved, kind/enhancement

#1167 fix: fix bug for no group time range
  src/metrics/basic.ts
Labels: pull/approved, kind/bug
