Repository X-lab2017/open-digger, pull requests merged in 2024-01, with the labels that each got.

#1460 fix: fix 2 bugs in cron task
  src/cron/tasks/monthly_export.ts
  src/cron/tasks/open_leaderboard.ts
Labels: kind/bug

#1461 fix: add priority users in update github users
  src/cron/tasks/update_github_users.ts
Labels: kind/bug

#1464 fix: fix platform error in sofastack
  labeled_data/companies/antgroup/sofastack.yml
Labels: kind/bug

#1487 Fix Bug: Correct labels of yaml files in labeled_data directory.
  labeled_data/technology/ai/generative_ai/application/audio.yml
  labeled_data/technology/ai/generative_ai/application/code.yml
  labeled_data/technology/ai/generative_ai/application/image.yml
  labeled_data/technology/ai/generative_ai/application/index.yml
  labeled_data/technology/ai/generative_ai/application/other.yml
  labeled_data/technology/ai/generative_ai/application/text.yml
  labeled_data/technology/ai/generative_ai/application/video.yml
  labeled_data/technology/ai/generative_ai/index.yml
  labeled_data/technology/ai/generative_ai/infrastructure/data.yml
  labeled_data/technology/ai/generative_ai/infrastructure/document.yml
  labeled_data/technology/ai/generative_ai/infrastructure/index.yml
  labeled_data/technology/ai/generative_ai/infrastructure/platform_and_environment.yml
  labeled_data/technology/ai/generative_ai/infrastructure/vector_database.yml
  labeled_data/technology/ai/generative_ai/model/framework_and_architecture.yml
  labeled_data/technology/ai/generative_ai/model/fundamental_model.yml
  labeled_data/technology/ai/generative_ai/model/index.yml
  labeled_data/technology/ai/generative_ai/model/variant_model.yml
  labeled_data/technology/ai/generative_ai/tool/deployment_tool.yml
  labeled_data/technology/ai/generative_ai/tool/develop_tool.yml
  labeled_data/technology/ai/generative_ai/tool/index.yml
  labeled_data/technology/ai/generative_ai/tool/production_monitor.yml
  labeled_data/technology/ai/generative_ai/tool/prompt_engineering.yml
  labeled_data/technology/ai/large_language_model/index.yml
  labeled_data/technology/cloud_native/app_definition_and_development/application_definition_and_image_build.yml
  labeled_data/technology/cloud_native/app_definition_and_development/continuous_integration_and_delivery.yml
  labeled_data/technology/cloud_native/platform/certified_kubernetes_distribution.yml
  labeled_data/technology/cloud_native/platform/certified_kubernetes_hosted.yml
  labeled_data/technology/cloud_native/platform/certified_kubernetes_installer.yml
  src/label_data_utils.ts
Labels: kind/bug

#1493 feat: add community openrank cron task
  package-lock.json
  package.json
  src/cron/tasks/community_openrank.ts
  src/db/clickhouse.ts
Labels: kind/community

#1502 feat: add columns into community openrank table
  src/cron/tasks/community_openrank.ts
Labels: kind/community

#1503 fix: fix community openrank org_id and org_login
  src/cron/tasks/community_openrank.ts
Labels: kind/bug, kind/community

#1505 feat: add community openrank metric interface
  src/metrics/index.ts
  src/metrics/indices.ts
  src/open_digger.js
Labels: kind/community

#1507 refactor: some minor refactors
  src/metrics/basic.ts
  src/open_digger.js
  src/utils.ts
Labels: kind/enhancement

#1508 refactor: add platform and actor_id in community openrank
  src/metrics/indices.ts
Labels: kind/enhancement, kind/community

#1509 fix: fix agg func for community openrank
  labeled_data/bot/index.yml
  src/metrics/indices.ts
Labels: kind/bug, kind/community

#1512 fix: fix alibaba project names
  labeled_data/companies/alibaba/havenask.yml
  labeled_data/companies/alibaba/ice.yml
  labeled_data/companies/alibaba/polardb-x.yml
Labels: kind/bug

#1516 refactor: fix type for github app and cron
  src/cron/index.ts
  src/cron/tasks/issue_reaction_importer.ts
Labels: kind/enhancement
